services:
  postgres:
    image: postgres:16-alpine
    container_name: db-foodstream
    restart: unless-stopped
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - back-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 3s
      timeout: 3s
      retries: 20

  backend:
    container_name: backend-foodstream
    depends_on:
      - postgres
    build: ./backend
    env_file: ./.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - back-network
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_PORT: ${BACKEND_PORT}


volumes:
  postgres_data:
    driver: local

networks:
  back-network:
    driver: bridge
